//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryFormManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRegister
    {
        public string cName { get; set; }
        public string userName { get; set; }
        public decimal phoneNo { get; set; }
        public string password { get; set; }
        public string city { get; set; }
    }
}
